// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ClubProfileProvider } from "@/context/ClubProfileContext";
// import { WatchAlongProvider } from "@/context/WatchAlongContext";
// import { SessionProvider } from "next-auth/react";
// import { PlayerProfile360Provider } from "@/context/PlayerProfile360Context";
// import { GlobalSearchProvider } from "@/context/GlobalSearchContext";
// import { AudioProvider } from "@/context/AudioContext";
// import { AuthProvider } from "@/context/AuthContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SessionProvider>
//           <ClubProfileProvider>
//             <WatchAlongProvider>
//               <PlayerProfile360Provider>
//                 <GlobalSearchProvider>
//                   <AudioProvider>
//                     <AuthProvider>
//                       {children}
//                     </AuthProvider>
//                   </AudioProvider>
//                 </GlobalSearchProvider>
//               </PlayerProfile360Provider>
//             </WatchAlongProvider>
//           </ClubProfileProvider>
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }








import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClubProfileProvider } from "@/context/ClubProfileContext";
import { WatchAlongProvider } from "@/context/WatchAlongContext";
import { SessionProvider } from "next-auth/react";
import { PlayerProfile360Provider } from "@/context/PlayerProfile360Context";
import { GlobalSearchProvider } from "@/context/GlobalSearchContext";
import { AudioProvider } from "@/context/AudioContext";
import { AuthProvider } from "@/context/AuthContext";
import { VideoProvider } from "@/context/VideoContext";
import { PlaysProvider } from "@/context/PlaysContext";
import { ScriptsProvider } from "@/context/ScriptsContext";
import GlobalActionBar from "@/src/components/GlobalActionBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SportsFan360",
  description: "Your Ultimate Sports Destination",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased !p-0`}
      >
        <SessionProvider>
          <ClubProfileProvider>
            <WatchAlongProvider>
              <PlayerProfile360Provider>
                <GlobalSearchProvider>
                  <AudioProvider>
                    <AuthProvider>
                      <VideoProvider>
                        <PlaysProvider>
                          <ScriptsProvider>
                            <main >{children}</main>
                          </ScriptsProvider>
                        </PlaysProvider>
                      </VideoProvider>
                    </AuthProvider>
                  </AudioProvider>
                </GlobalSearchProvider>
              </PlayerProfile360Provider>
            </WatchAlongProvider>
          </ClubProfileProvider>
        </SessionProvider>
        <GlobalActionBar />
      </body>
    </html>
  );
}
